recentCommunityTopicCommentForProfile:
  caption:
    ja_JP: "書き込み一覧"
  description:
    ja_JP: "プロフィールを表示中のメンバーが書き込んだコミュニティトピックの一覧を表示します"
  component: [communityTopic, topicCommentByMemberListBox]
  config:
    col:
      Name:       "col"
      Caption:    "表示するトピック数"
      FormType:   "select"
      ValueType:  "integer"
      IsRequired: true
      Default:    5
      Choices:    {1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8, 9: 9, 10: 10}
